services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: users_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend-service:
    container_name: auth
    image: auth
    env_file:
      - ./src/Auth.API/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:5181"
    depends_on:
      - postgres

volumes:
  postgres-data: